kind: Pod
apiVersion: v1
metadata:
  name: nginx-phpfpm
spec:
  volumes:
  # Create the shared files volume to be used in both pods
  - name: shared-files
    emptyDir: {}
    
  # Add the ConfigMap 'nginx-config-volume' as a volume for the pod
  - name: nginx-config-volume
    configMap:
    name: nginx-config

  containers:
  - image: php:7.1-fpm
    name: php-fpm-container
    volumeMounts:
    - name: shared-files
      mountPath: /var/www/html
  - image: nginx:latest
    name: nginx-container 
    volumeMounts:
    - name: shared-files
      mountPath: /var/www/html
    - name: nginx-config-volume
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
